(function() {var implementors = {};
implementors['rawinput'] = ["impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rawinput/event/enum.State.html' title='rawinput::event::State'>State</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rawinput/event/enum.KeyId.html' title='rawinput::event::KeyId'>KeyId</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rawinput/event/enum.MouseButton.html' title='rawinput::event::MouseButton'>MouseButton</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='enum' href='rawinput/event/enum.RawEvent.html' title='rawinput::event::RawEvent'>RawEvent</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rawinput/struct.Mouse.html' title='rawinput::Mouse'>Mouse</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rawinput/struct.Keyboard.html' title='rawinput::Keyboard'>Keyboard</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rawinput/struct.Hid.html' title='rawinput::Hid'>Hid</a>","impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='rawinput/struct.Devices.html' title='rawinput::Devices'>Devices</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
